### PR TITLE
Add Chord length Test

### PR DESCRIPTION
**Pull request by nukenukenukelol**
Add chord length test to the spherical case. The logic is similar to the polar one. We first find the expected chord length via the entry and exit time calculation. Then, we use an accumulator to keep track of total time we spend on traversal.

### CODE REVIEW

**Comment by cgyurgyik** [comment]
I'm sorry, I'm still a bit lost on this. How would I actually write a unit test using this? Is there any way to add chord length tests to our testing .m file?

**Comment by ak-2485** [comment]
@cgyurgyik our function could output [rVoxels, thetaVoxels, phiVoxels, **traversal time**] and we could then have a verification on this value where the expected value is calculated externally in a different function.

**Comment by ak-2485** [comment]
@nukenukenukelol @cgyurgyik after you review the PR #103 can @nukenukenukelol migrate the above into the new code?

**Comment by nukenukenukelol** [comment]
> @nukenukenukelol @cgyurgyik after you review the PR #103 can @nukenukenukelol migrate the above into the new code?

Yes will do

**Pull request closed without merging**
